title: Rory Smith O.D.
logo: /design-in-progress/snowy.jpg
description: "Never attribute to malice that which can be adequately explained by stupidity. Never underestimate the power of human stupidity." – Robert Heinlein

Hosted on GitHub Pages — Theme by orderedlist

show_downloads: false
theme: jekyll-theme-minimal
